language: java

sudo: false # faster builds

services:
  - mysql # start mysql service

before_install:
  - pip install --user codecov
  - mysql -e 'CREATE DATABASE springboot;' # create database springboot

after_success:
  - codecov